version: 3

tasks:
  build:
    cmds:
      - docker build -t bruxiz/wimi:{{.VERSION}} -t bruxiz/wimi:latest .
    description: Build the Docker image

  publish:
    cmds:
      - docker build -t {{.REGISTRY}}/wimi:{{.VERSION}} -t {{.REGISTRY}}/wimi:latest .
      - docker login -u {{.DOCKER_USERNAME}} -p {{.DOCKER_PASSWORD}}
      - docker push --all-tags {{.REGISTRY}}/wimi:{{.VERSION}}
    description: Publish the Docker image

  test:
    cmds:
      - pip3 install -r requirements.txt
      - python3 -m unittest test_app.py
    description: Run tests


options:
  version:
    description: Version tag for the Docker image
    required: true
    default: "latest"

  registry_url:
    description: Docker container registry URL
    required: true
    default: ""

  username:
    description: Docker registry username
    required: true
    default: ""

  password:
    description: Docker registry password
    required: true
    default: ""
