version: 3

tasks:
  build:
    cmds:
      - docker build -t bruxiz/wimi:{{.VERSION}} -t bruxiz/wimi:latest .
    description: Build the Docker image

  publish:
    cmds:
      - docker build -t {{.REGISTRY}}/wimi:{{.VERSION}} -t {{.REGISTRY}}/wimi:latest .
      - docker login -u {{.DOCKER_USERNAME}} -p {{.DOCKER_PASSWORD}}
      - docker push {{.REGISTRY}}/wimi:{{.VERSION}}
      - docker push {{.REGISTRY}}/wimi:latest
    description: Publish the Docker image

  test:
    cmds:
      - pip3 install -r requirements.txt
      - python3 -m unittest test_app.py
    description: Run tests

