version: 3

tasks:
  build:
    cmds:
      - docker build -t wimi:${ARGS.version} .
    description: Build the Docker image

  publish:
    cmds:
      - docker tag wimi:${ARGS.version} ${ARGS.registry_url}/wimi:${ARGS.version}
      - docker login -u ${ARGS.username} -p ${ARGS.password} ${ARGS.registry_url}
      - docker push ${ARGS.registry_url}/wimi:${ARGS.version}
    description: Publish the Docker image

  test:
    cmds:
      - pip3 install -r requirements.txt
      - python3 -m unittest test_app.py
    description: Run unit tests

  pull-request:
    cmds:
      - task test
      - task build
    description: Run tests and build

  merge:
    cmds:
      - task build
      - task publish
    description: Run build and publish

options:
  version:
    description: Version tag for the Docker image
    required: true
    default: "latest"

  registry_url:
    description: Docker container registry URL
    required: true
    default: ""

  username:
    description: Docker registry username
    required: true
    default: ""

  password:
    description: Docker registry password
    required: true
    default: ""
