{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.namePrefix }}-ingress
spec:
  rules:
    - host: {{ .Values.ingressHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.namePrefix }}-service
                port:
                  number: {{ .Values.servicePort }}
{{- end }}
