apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.namePrefix }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
