apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.namePrefix }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
