apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-service
spec:
  selector:
    app: {{ .Values.namePrefix }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
